name: finc
description: "A expense tracking and portfolio management app."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  adaptive_navigation: ^0.0.10
  cloud_firestore: ^5.6.0
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.6.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
