// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs-lQxNHnqYsxmlYcjHrqug8OD_N1S1M8',
    appId: '1:991764411499:web:6f122d40958d38d2b3ed2e',
    messagingSenderId: '991764411499',
    projectId: 'ncfinance',
    authDomain: 'ncfinance.firebaseapp.com',
    storageBucket: 'ncfinance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ntIWrNXbPZWa1V_P6IEwa7N0vO4INu4',
    appId: '1:991764411499:android:960a0f1de9f1ea94b3ed2e',
    messagingSenderId: '991764411499',
    projectId: 'ncfinance',
    storageBucket: 'ncfinance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPNPPieBYfXGxVcw5c08gRfLHOQlvN-mM',
    appId: '1:991764411499:ios:e138eea22b7e81e8b3ed2e',
    messagingSenderId: '991764411499',
    projectId: 'ncfinance',
    storageBucket: 'ncfinance.firebasestorage.app',
    iosBundleId: 'com.example.finc',
  );
}
